### ISSUE TITLE
iNav index page - tag layer always swing when mouse hover tag text

### ISSUE THREAD

**Issue by itabas016** [itabas016/sitenav#1]
It's better add a restrict adjustment width/height for tag

``` css
.tag {
    width: 30px;
    height: 25px;
}
```
